import { useState } from "react";
import { Link } from "react-router-dom";
import {
  Search,
  Bell,
  ChevronDown,
  FileText,
  Download,
  BarChart3,
  Clock,
  CheckCircle,
  X,
  TrendingUp,
  ShieldAlert,
} from "lucide-react";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

const initialReports = [
  {
    id: "RPT-2026-0915",
    name: "Daily Cybercrime Risk Report",
    type: "Risk Analysis",
    generated: "15 Sep 2026, 14:30",
    generatedBy: "Admin Officer",
    status: "Ready",
  },
  {
    id: "RPT-2026-0914",
    name: "Cash Withdrawal Prediction Report",
    type: "Prediction",
    generated: "14 Sep 2026, 18:15",
    generatedBy: "Insp. A. Patil",
    status: "Ready",
  },
  {
    id: "RPT-2026-0913",
    name: "High Risk Location Report",
    type: "GIS Intelligence",
    generated: "13 Sep 2026, 16:45",
    generatedBy: "PSI R. Singh",
    status: "Ready",
  },
];

const chartData = [
  { name: "UPI", cases: 42 },
  { name: "Banking", cases: 31 },
  { name: "Investment", cases: 24 },
  { name: "Phishing", cases: 18 },
  { name: "Card", cases: 15 },
];

function Reports() {
  const [reports, setReports] = useState(initialReports);
  const [typeFilter, setTypeFilter] = useState("All");
  const [showToast, setShowToast] = useState(false);

  const filteredReports =
    typeFilter === "All"
      ? reports
      : reports.filter((report) => report.type === typeFilter);

  const generateReport = () => {
    const newReport = {
      id: `RPT-2026-${916 + reports.length}`,
      name: "New Cybercrime Intelligence Report",
      type: "Risk Analysis",
      generated: "16 Sep 2026, 15:30",
      generatedBy: "Admin Officer",
      status: "Ready",
    };

    setReports([newReport, ...reports]);
    setShowToast(true);

    setTimeout(() => setShowToast(false), 2500);
  };

  const downloadReport = (report) => {
    const content =
      `Cybercrime Intelligence Report\n\n` +
      `Report ID: ${report.id}\n` +
      `Report Name: ${report.name}\n` +
      `Type: ${report.type}\n` +
      `Generated: ${report.generated}\n` +
      `Generated By: ${report.generatedBy}\n` +
      `Status: ${report.status}\n`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.id}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <div className="reference-dashboard">

      {/* HEADER */}
      <header className="reference-header">

        <div className="team-brand">
          <div className="team-logo-placeholder">🛡</div>

          <div>
            <strong>CYBER INTELLIGENCE CELL</strong>
            <span>Predictive Cybercrime Analytics</span>
          </div>
        </div>

        <div className="platform-brand">
          <h2>Cybercrime Predictive Intelligence Platform</h2>
          <p>Law Enforcement Intelligence &amp; Analytics</p>
        </div>

        <div className="header-right-section">

          <span className="safety-text">
            SECURE • AUTHORIZED ACCESS ONLY
          </span>

          <div className="header-divider"></div>

          <Bell size={18} />

          <div className="profile-section">
            <div className="profile-avatar">AO</div>

            <div>
              <strong>Admin Officer</strong>
              <span>Cyber Intelligence Cell</span>
            </div>

            <ChevronDown size={15} />
          </div>

        </div>
      </header>

      {/* NAVIGATION */}
      <nav className="top-navigation">

        <div className="nav-left">

          <Link to="/dashboard">Dashboard</Link>
          <Link to="/cases">Cases</Link>
          <Link to="/predictions">Predictions</Link>
          <Link to="/gis">GIS Intelligence</Link>
          <Link to="/alerts">Alerts</Link>

          <Link to="/reports" className="active-nav">
            Reports
          </Link>

          <Link to="/users">Users</Link>
          <Link to="/audit-logs">Audit Logs</Link>

        </div>

        <div className="nav-search">
          <Search size={14} />
          <input placeholder="Search cases, locations, reports..." />
        </div>

      </nav>

      {/* CONTENT */}
      <main className="reference-content">

        {/* PAGE HEADING */}
        <div className="reference-page-heading">

          <div>
            <h1>Reports</h1>

            <p>
              Generate and review cybercrime intelligence and analytical
              reports.
            </p>
          </div>

          <div
            style={{
              fontSize: "12px",
              color: "#647687",
            }}
          >
            Last updated: 16 Sep 2026, 15:30
          </div>

        </div>

        {/* QUICK INSIGHT BANNER */}
        <div
          style={{
            background:
              "linear-gradient(90deg, #eaf4ff 0%, #f4f9fd 100%)",
            border: "1px solid #cbdfee",
            borderLeft: "4px solid #1671b8",
            borderRadius: "8px",
            padding: "13px 16px",
            marginBottom: "18px",
            display: "flex",
            alignItems: "center",
            gap: "12px",
          }}
        >
          <div
            style={{
              width: "34px",
              height: "34px",
              borderRadius: "7px",
              background: "#d8ebfa",
              color: "#0b5f98",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <TrendingUp size={18} />
          </div>

          <div>
            <strong
              style={{
                color: "#173f63",
                fontSize: "13px",
              }}
            >
              Intelligence Reporting Overview
            </strong>

            <p
              style={{
                margin: "3px 0 0",
                color: "#607282",
                fontSize: "11px",
              }}
            >
              Reports provide analytical insights for cybercrime
              investigation and proactive intervention.
            </p>
          </div>
        </div>

        {/* TOOLBAR */}
        <div className="reports-toolbar">

          <div className="report-filter">
            <FileText size={15} />

            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              style={{
                border: "none",
                background: "transparent",
                outline: "none",
                color: "#526574",
                fontSize: "13px",
              }}
            >
              <option value="All">All Report Types</option>
              <option value="Risk Analysis">Risk Analysis</option>
              <option value="Prediction">Prediction</option>
              <option value="GIS Intelligence">
                GIS Intelligence
              </option>
            </select>
          </div>

          <button
            className="generate-report"
            onClick={generateReport}
          >
            <BarChart3 size={16} />
            Generate Report
          </button>

        </div>

        {/* STATS */}
        <div className="report-stats">

          <div
            className="report-stat-card"
            style={{ borderTop: "3px solid #1671b8" }}
          >
            <div
              className="report-stat-icon"
              style={{
                background: "#e4f1fb",
                color: "#1671b8",
              }}
            >
              <FileText size={21} />
            </div>

            <div>
              <span>Total Reports</span>
              <strong>{reports.length}</strong>
              <small>Generated</small>
            </div>
          </div>

          <div
            className="report-stat-card"
            style={{ borderTop: "3px solid #2c9b68" }}
          >
            <div
              className="report-stat-icon"
              style={{
                background: "#e5f6ed",
                color: "#2c9b68",
              }}
            >
              <CheckCircle size={21} />
            </div>

            <div>
              <span>Ready Reports</span>
              <strong>
                {reports.filter((r) => r.status === "Ready").length}
              </strong>
              <small>Available</small>
            </div>
          </div>

          <div
            className="report-stat-card"
            style={{ borderTop: "3px solid #e59b24" }}
          >
            <div
              className="report-stat-icon"
              style={{
                background: "#fff3dc",
                color: "#d88912",
              }}
            >
              <ShieldAlert size={21} />
            </div>

            <div>
              <span>High Risk Cases</span>
              <strong>186</strong>
              <small>Require attention</small>
            </div>
          </div>

          <div
            className="report-stat-card"
            style={{ borderTop: "3px solid #7256a5" }}
          >
            <div
              className="report-stat-icon"
              style={{
                background: "#eee9f8",
                color: "#7256a5",
              }}
            >
              <Clock size={21} />
            </div>

            <div>
              <span>Last Updated</span>
              <strong>15:30</strong>
              <small>Today</small>
            </div>
          </div>

        </div>

        {/* CHARTS */}
        <div className="reports-chart-grid">

          <div className="reference-card">

            <div className="reference-card-header">
              <div>
                <h3>Cases by Crime Category</h3>
                <p>
                  Current reported cybercrime distribution
                </p>
              </div>

              <div
                style={{
                  background: "#eaf4fb",
                  color: "#0b5f98",
                  padding: "5px 9px",
                  borderRadius: "5px",
                  fontSize: "10px",
                  fontWeight: "600",
                }}
              >
                LIVE DATA
              </div>
            </div>

            <div className="report-chart">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Bar
                    dataKey="cases"
                    fill="#1671b8"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>

          </div>

          <div className="reference-card">

            <div className="reference-card-header">
              <div>
                <h3>Report Information</h3>
                <p>Intelligence reporting status</p>
              </div>
            </div>

            <div style={{ padding: "18px" }}>

              <InfoRow
                label="Data coverage"
                value="Pune District"
              />

              <InfoRow
                label="Prediction window"
                value="Next 24 Hours"
              />

              <InfoRow
                label="Reports generated"
                value={`${reports.length} Reports`}
              />

              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  padding: "12px 0",
                }}
              >
                <span
                  style={{
                    color: "#607282",
                    fontSize: "13px",
                  }}
                >
                  Intelligence status
                </span>

                <span
                  style={{
                    background: "#e5f6ed",
                    color: "#26764d",
                    padding: "5px 10px",
                    borderRadius: "12px",
                    fontSize: "10px",
                    fontWeight: "700",
                  }}
                >
                  ACTIVE
                </span>
              </div>

            </div>

          </div>

        </div>

        {/* REPORT TABLE */}
        <div className="reference-card">

          <div className="reference-card-header">

            <div>
              <h3>Generated Reports</h3>
              <p>
                Previously generated intelligence reports
              </p>
            </div>

            <div
              style={{
                background: "#f1f6fa",
                color: "#526574",
                padding: "6px 10px",
                borderRadius: "5px",
                fontSize: "11px",
              }}
            >
              {filteredReports.length} records
            </div>

          </div>

          <div className="reports-table">

            <table>

              <thead>
                <tr>
                  <th>Report ID</th>
                  <th>Report Name</th>
                  <th>Type</th>
                  <th>Generated</th>
                  <th>Generated By</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>

                {filteredReports.map((report) => (

                  <tr key={report.id}>

                    <td>
                      <span
                        style={{
                          color: "#0b5f98",
                          fontWeight: "600",
                        }}
                      >
                        {report.id}
                      </span>
                    </td>

                    <td>
                      <strong>{report.name}</strong>
                    </td>

                    <td>
                      <span
                        style={{
                          background: "#edf5fb",
                          color: "#386681",
                          padding: "4px 8px",
                          borderRadius: "4px",
                          fontSize: "10px",
                          fontWeight: "600",
                        }}
                      >
                        {report.type}
                      </span>
                    </td>

                    <td>{report.generated}</td>

                    <td>{report.generatedBy}</td>

                    <td>
                      <span className="report-ready">
                        {report.status}
                      </span>
                    </td>

                    <td>
                      <button
                        className="download-report"
                        onClick={() => downloadReport(report)}
                      >
                        <Download size={14} />
                        Download
                      </button>
                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        </div>

        {/* SECURITY NOTE */}
        <div
          style={{
            marginTop: "18px",
            padding: "13px 16px",
            background: "#fff8e8",
            border: "1px solid #f0d99c",
            borderRadius: "7px",
            fontSize: "12px",
            color: "#6d5a32",
            display: "flex",
            alignItems: "center",
            gap: "9px",
          }}
        >
          <ShieldAlert size={16} />

          <span>
            <strong style={{ color: "#765b1f" }}>
              Security Notice:
            </strong>{" "}
            Reports contain restricted law-enforcement intelligence.
            Access and downloads are recorded in the Audit Logs.
          </span>
        </div>

      </main>

      {/* TOAST */}
      {showToast && (

        <div
          style={{
            position: "fixed",
            right: "25px",
            bottom: "25px",
            background: "#173f63",
            color: "white",
            padding: "13px 18px",
            borderRadius: "7px",
            display: "flex",
            alignItems: "center",
            gap: "9px",
            boxShadow: "0 5px 20px rgba(0,0,0,0.18)",
            fontSize: "13px",
            zIndex: 1000,
          }}
        >
          <CheckCircle size={17} />
          Report generated successfully

          <X
            size={15}
            style={{ cursor: "pointer" }}
            onClick={() => setShowToast(false)}
          />
        </div>

      )}

    </div>
  );
}

function InfoRow({ label, value }) {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        padding: "12px 0",
        borderBottom: "1px solid #e5ebf0",
      }}
    >
      <span
        style={{
          color: "#607282",
          fontSize: "13px",
        }}
      >
        {label}
      </span>

      <strong
        style={{
          color: "#173f63",
          fontSize: "12px",
        }}
      >
        {value}
      </strong>
    </div>
  );
}

export default Reports;